---
abstract: 'Translator for biological identifiers'
author:
  - 'Nat Goodman <natg@shore.net>'
build_requires:
  Carp: 1.2
  Class::AutoClass: 1.55
  Class::AutoDB: 1.28
  Clone: 0.35
  Cwd: 3.4
  DBI: 1.628
  English: 1.04
  Exporter: 5.68
  File::Basename: 2.82
  File::Spec: 3.4
  File::Spec::Functions: 3.4
  FindBin: 1.5
  Getopt::Long: 2.38
  Graph: 0.96
  Hash::AutoHash: 1.16
  Hash::AutoHash::Args: 1.17
  List::MoreUtils: 0.33
  List::Util: 1.23
  Math::BaseCalc: 1.014
  Module::Build: 0.4007
  POSIX: 1.24
  Scalar::Util: 1.23
  TAP::Formatter::Console: 3.28
  TAP::Harness: 3.28
  TAP::Parser::Aggregator: 3.28
  Test::CheckManifest: 1.26
  Test::Deep: 0.11
  Test::More: 0.98
  Test::Pod: 1.48
  Test::Pod::Content: v0.0.6
  Text::Abbrev: 1.02
  Text::Balanced: 2.02
configure_requires:
  Module::Build: 0.4007
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Babel
provides:
  Data::Babel:
    file: lib/Data/Babel.pm
    version: 1.13
  Data::Babel::Base:
    file: lib/Data/Babel/Base.pm
    version: 0
  Data::Babel::Config:
    file: lib/Data/Babel/Config.pm
    version: 0
  Data::Babel::Filter:
    file: lib/Data/Babel/Filter.pm
    version: 0
  Data::Babel::HAH_MultiValued:
    file: lib/Data/Babel/HAH_MultiValued.pm
    version: 0
  Data::Babel::HAH_MultiValued::helper:
    file: lib/Data/Babel/HAH_MultiValued.pm
    version: 0
  Data::Babel::HAH_MultiValued::tie:
    file: lib/Data/Babel/HAH_MultiValued.pm
    version: 0
  Data::Babel::IdType:
    file: lib/Data/Babel/IdType.pm
    version: 0
  Data::Babel::MapTable:
    file: lib/Data/Babel/MapTable.pm
    version: 0
  Data::Babel::Master:
    file: lib/Data/Babel/Master.pm
    version: 0
  Data::Babel::PrefixMatcher:
    file: lib/Data/Babel/PrefixMatcher.pm
    version: 0
  Data::Babel::PrefixMatcher::BinarySearchList:
    file: lib/Data/Babel/PrefixMatcher/BinarySearchList.pm
    version: 0
  Data::Babel::PrefixMatcher::BinarySearchTree:
    file: lib/Data/Babel/PrefixMatcher/BinarySearchTree.pm
    version: 0
  Data::Babel::PrefixMatcher::Exact:
    file: lib/Data/Babel/PrefixMatcher/Exact.pm
    version: 0
  Data::Babel::PrefixMatcher::PrefixHash:
    file: lib/Data/Babel/PrefixMatcher/PrefixHash.pm
    version: 0
  Data::Babel::PrefixMatcher::Trie:
    file: lib/Data/Babel/PrefixMatcher/Trie.pm
    version: 0
recommends:
  List::BinarySearch: 0.14
  Tree::RB: 0.500004
requires:
  AutoLoader: 5.71
  B: 1.29
  B::Deparse: 1.04
  Carp: 1.2
  Class::AutoClass: 1.55
  Class::AutoDB: 1.28
  Class::Singleton: 1.4
  Config::IniFiles: 2.82
  Cwd: 3.4
  DBD::mysql: 4.024
  DBI: 1.628
  Data::Dumper: 2.145
  Exporter: 5.68
  File::Basename: 2.82
  File::Path: 2.07
  File::Spec: 3.4
  File::Temp: 0.2302
  Graph: 0.96
  Hash::AutoHash: 1.16
  Hash::AutoHash::Args: 1.17
  Hash::AutoHash::MultiValued: 1.16
  List::Categorize: 0.03
  List::MoreUtils: 0.33
  List::Util: 1.32
  Safe: 2.35
  Storable: 2.3
  Template: 2.25
  Text::Abbrev: 1.02
  Tie::ToObject: 0.03
  Tree::Trie: 1.9
  XSLoader: 0.16
resources:
  license: http://dev.perl.org/licenses/
version: 1.13
