---
abstract: 'Translator for biological identifiers'
author:
  - 'Nat Goodman <natg@shore.net>'
build_requires:
  Carp: 0
  Class::AutoClass: 1.53
  Config: 0
  Cwd: 3.26
  DBI: 1.604
  Exporter: 5.58
  File::Basename: 0
  File::Spec: 3.26
  File::Spec::Functions: 3.26
  FindBin: 0
  Getopt::Long: 2.13
  Graph: 0.91
  Hash::AutoHash: 1.15
  Hash::AutoHash::Args: 1.14
  Hash::AutoHash::MultiValued: 1.14
  List::MoreUtils: 0.09
  List::Util: 1.14
  Math::BaseCalc: 1.009
  Scalar::Util: 1.01
  Set::Scalar: 1.22
  Storable: 2.16
  TAP::Harness: 3.12
  Test::Deep: 0.11
  Test::More: 0.88
  Text::Abbrev: 1.01
configure_requires:
  DBI: 1.604
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Babel
provides:
  Data::Babel:
    file: lib/Data/Babel.pm
    version: 1.10_04
  Data::Babel::Base:
    file: lib/Data/Babel/Base.pm
    version: 0
  Data::Babel::Config:
    file: lib/Data/Babel/Config.pm
    version: 0
  Data::Babel::HAH_MultiValued:
    file: lib/Data/Babel/HAH_MultiValued.pm
    version: 0
  Data::Babel::HAH_MultiValued::helper:
    file: lib/Data/Babel/HAH_MultiValued.pm
    version: 0
  Data::Babel::HAH_MultiValued::tie:
    file: lib/Data/Babel/HAH_MultiValued.pm
    version: 0
  Data::Babel::IdType:
    file: lib/Data/Babel/IdType.pm
    version: 0
  Data::Babel::MapTable:
    file: lib/Data/Babel/MapTable.pm
    version: 0
  Data::Babel::Master:
    file: lib/Data/Babel/Master.pm
    version: 0
requires:
  Carp: 0
  Class::AutoClass: 1.53
  Class::AutoDB: 1.2
  Config::IniFiles: 2.57
  DBI: 1.604
  File::Basename: 0
  File::Spec: 3.26
  Graph: 0.91
  Hash::AutoHash: 1.15
  Hash::AutoHash::Args: 1.14
  Hash::AutoHash::MultiValued: 1.14
  List::MoreUtils: 0.09
  Template: 2.2
resources:
  license: http://dev.perl.org/licenses/
version: 1.10_04
